[package]
name = "tts_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
image = "0.25.5"
pdf2image = "0.1.2"
rayon = "1.10.0"
regex = "1.11.1"
sherpa-rs = { version = "0.6.5", features = ["tts"] }
tesseract = "0.15.1"
