// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	setDefaultModel: (modelName: string) => typedError<null, Error>(__TAURI_INVOKE("set_default_model", { modelName })),
	getConfig: () => typedError<TtsAppConfig, Error>(__TAURI_INVOKE("get_config")),
	getDownloadedModels: () => typedError<string[], Error>(__TAURI_INVOKE("get_downloaded_models")),
	runJob: (job: TtsJobConfig, progressReader: Channel<TtsGenerationProgress>) => typedError<null, Error>(__TAURI_INVOKE("run_job", { job, progressReader })),
	getCompletedOnboarding: () => typedError<boolean, Error>(__TAURI_INVOKE("get_completed_onboarding")),
	setCompletedOnboarding: (request: CompletedOnboardingRequest) => typedError<null, Error>(__TAURI_INVOKE("set_completed_onboarding", { request })),
};

/* Types */
export type CompletedOnboardingRequest = boolean;

export type Error = string;

export type TtsAppConfig = {
	/**  start the narration at a certain page */
	output_dir: string,
	start_page: number,
	output_prefix: string,
	voice: string,
	speed: number | null,
	combine_pages: boolean,
	speaker_id: number,
};

export type TtsGenerationProgress = { event: "inProgress"; data: number | null } | { event: "finished" };

export type TtsJobConfig = {
	output_prefix: string,
	output_dir: string,
	start_page: number,
	/**  sets a voice for the narration. see https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/index.html */
	voice: string,
	speed: number | null,
	combine_pages: boolean,
	/**  for voices that have multiple speakers, pass a speaker_id. */
	speaker_id: number,
	use_ocr: boolean,
	input_file: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

