name: Build (Linux)

on:
  push:
    branches: ["neo"]
  pull_request:
    branches: ["neo"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Output Git Release
        run: | 
          echo ${{ github.sha }} > Release.txt \
          && echo "RELEASE_VERSION=$(git rev-parse --short HEAD)" | tee -a $GITHUB_ENV
      - name: Update packages
        run: sudo apt update

      - name: Install TTS dependencies (onnxruntime +)
        run: |
          sudo apt-get install -y \
          libonnxruntime-dev \
          libstdc++6 \
          libleptonica-dev \
          libtesseract-dev \
          libglib2.0-dev \
          libgtk-3-dev \
          libsoup-3.0-dev \
          libjavascriptcoregtk-4.1-dev
      - name: Install yarn dependencies
        run: yarn --frozen-lockfile
      - name: Build (Linux)
        run: yarn tauri build
    #   - name: Run tests
        # run: cargo test --verbose
      - name: Upload release
        uses: softprops/action-gh-release@v3
        with: 
          tag_name: ${{env.RELEASE_VERSION}}
          files: |
            Release.txt
            target/release/drp
